package com.zx.card.model;

import java.util.Date;

public class AssetHistory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_asset_history.id
     *
     * @mbggenerated Sat Apr 25 18:05:45 CST 2020
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_asset_history.card_id
     *
     * @mbggenerated Sat Apr 25 18:05:45 CST 2020
     */
    private Long cardId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_asset_history.event_id
     *
     * @mbggenerated Sat Apr 25 18:05:45 CST 2020
     */
    private Long eventId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_asset_history.event
     *
     * @mbggenerated Sat Apr 25 18:05:45 CST 2020
     */
    private String event;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_asset_history.pay_amt
     *
     * @mbggenerated Sat Apr 25 18:05:45 CST 2020
     */
    private Float payAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_asset_history.status
     *
     * @mbggenerated Sat Apr 25 18:05:45 CST 2020
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_asset_history.createtime
     *
     * @mbggenerated Sat Apr 25 18:05:45 CST 2020
     */
    private Date createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_asset_history.id
     *
     * @return the value of sc_asset_history.id
     *
     * @mbggenerated Sat Apr 25 18:05:45 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_asset_history.id
     *
     * @param id the value for sc_asset_history.id
     *
     * @mbggenerated Sat Apr 25 18:05:45 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_asset_history.card_id
     *
     * @return the value of sc_asset_history.card_id
     *
     * @mbggenerated Sat Apr 25 18:05:45 CST 2020
     */
    public Long getCardId() {
        return cardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_asset_history.card_id
     *
     * @param cardId the value for sc_asset_history.card_id
     *
     * @mbggenerated Sat Apr 25 18:05:45 CST 2020
     */
    public void setCardId(Long cardId) {
        this.cardId = cardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_asset_history.event_id
     *
     * @return the value of sc_asset_history.event_id
     *
     * @mbggenerated Sat Apr 25 18:05:45 CST 2020
     */
    public Long getEventId() {
        return eventId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_asset_history.event_id
     *
     * @param eventId the value for sc_asset_history.event_id
     *
     * @mbggenerated Sat Apr 25 18:05:45 CST 2020
     */
    public void setEventId(Long eventId) {
        this.eventId = eventId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_asset_history.event
     *
     * @return the value of sc_asset_history.event
     *
     * @mbggenerated Sat Apr 25 18:05:45 CST 2020
     */
    public String getEvent() {
        return event;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_asset_history.event
     *
     * @param event the value for sc_asset_history.event
     *
     * @mbggenerated Sat Apr 25 18:05:45 CST 2020
     */
    public void setEvent(String event) {
        this.event = event == null ? null : event.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_asset_history.pay_amt
     *
     * @return the value of sc_asset_history.pay_amt
     *
     * @mbggenerated Sat Apr 25 18:05:45 CST 2020
     */
    public Float getPayAmt() {
        return payAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_asset_history.pay_amt
     *
     * @param payAmt the value for sc_asset_history.pay_amt
     *
     * @mbggenerated Sat Apr 25 18:05:45 CST 2020
     */
    public void setPayAmt(Float payAmt) {
        this.payAmt = payAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_asset_history.status
     *
     * @return the value of sc_asset_history.status
     *
     * @mbggenerated Sat Apr 25 18:05:45 CST 2020
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_asset_history.status
     *
     * @param status the value for sc_asset_history.status
     *
     * @mbggenerated Sat Apr 25 18:05:45 CST 2020
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_asset_history.createtime
     *
     * @return the value of sc_asset_history.createtime
     *
     * @mbggenerated Sat Apr 25 18:05:45 CST 2020
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_asset_history.createtime
     *
     * @param createtime the value for sc_asset_history.createtime
     *
     * @mbggenerated Sat Apr 25 18:05:45 CST 2020
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
}