package com.zx.card.model;

import java.util.Date;

public class Book {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_book.id
     *
     * @mbggenerated Wed Apr 29 13:02:59 CST 2020
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_book.type_id
     *
     * @mbggenerated Wed Apr 29 13:02:59 CST 2020
     */
    private Long typeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_book.name
     *
     * @mbggenerated Wed Apr 29 13:02:59 CST 2020
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_book.author
     *
     * @mbggenerated Wed Apr 29 13:02:59 CST 2020
     */
    private String author;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_book.type_name
     *
     * @mbggenerated Wed Apr 29 13:02:59 CST 2020
     */
    private String typeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_book.publish_name
     *
     * @mbggenerated Wed Apr 29 13:02:59 CST 2020
     */
    private String publishName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_book.price
     *
     * @mbggenerated Wed Apr 29 13:02:59 CST 2020
     */
    private Float price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_book.book_num
     *
     * @mbggenerated Wed Apr 29 13:02:59 CST 2020
     */
    private Integer bookNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_book.status
     *
     * @mbggenerated Wed Apr 29 13:02:59 CST 2020
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_book.create_time
     *
     * @mbggenerated Wed Apr 29 13:02:59 CST 2020
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_book.update_time
     *
     * @mbggenerated Wed Apr 29 13:02:59 CST 2020
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_book.id
     *
     * @return the value of sc_book.id
     *
     * @mbggenerated Wed Apr 29 13:02:59 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_book.id
     *
     * @param id the value for sc_book.id
     *
     * @mbggenerated Wed Apr 29 13:02:59 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_book.type_id
     *
     * @return the value of sc_book.type_id
     *
     * @mbggenerated Wed Apr 29 13:02:59 CST 2020
     */
    public Long getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_book.type_id
     *
     * @param typeId the value for sc_book.type_id
     *
     * @mbggenerated Wed Apr 29 13:02:59 CST 2020
     */
    public void setTypeId(Long typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_book.name
     *
     * @return the value of sc_book.name
     *
     * @mbggenerated Wed Apr 29 13:02:59 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_book.name
     *
     * @param name the value for sc_book.name
     *
     * @mbggenerated Wed Apr 29 13:02:59 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_book.author
     *
     * @return the value of sc_book.author
     *
     * @mbggenerated Wed Apr 29 13:02:59 CST 2020
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_book.author
     *
     * @param author the value for sc_book.author
     *
     * @mbggenerated Wed Apr 29 13:02:59 CST 2020
     */
    public void setAuthor(String author) {
        this.author = author == null ? null : author.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_book.type_name
     *
     * @return the value of sc_book.type_name
     *
     * @mbggenerated Wed Apr 29 13:02:59 CST 2020
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_book.type_name
     *
     * @param typeName the value for sc_book.type_name
     *
     * @mbggenerated Wed Apr 29 13:02:59 CST 2020
     */
    public void setTypeName(String typeName) {
        this.typeName = typeName == null ? null : typeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_book.publish_name
     *
     * @return the value of sc_book.publish_name
     *
     * @mbggenerated Wed Apr 29 13:02:59 CST 2020
     */
    public String getPublishName() {
        return publishName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_book.publish_name
     *
     * @param publishName the value for sc_book.publish_name
     *
     * @mbggenerated Wed Apr 29 13:02:59 CST 2020
     */
    public void setPublishName(String publishName) {
        this.publishName = publishName == null ? null : publishName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_book.price
     *
     * @return the value of sc_book.price
     *
     * @mbggenerated Wed Apr 29 13:02:59 CST 2020
     */
    public Float getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_book.price
     *
     * @param price the value for sc_book.price
     *
     * @mbggenerated Wed Apr 29 13:02:59 CST 2020
     */
    public void setPrice(Float price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_book.book_num
     *
     * @return the value of sc_book.book_num
     *
     * @mbggenerated Wed Apr 29 13:02:59 CST 2020
     */
    public Integer getBookNum() {
        return bookNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_book.book_num
     *
     * @param bookNum the value for sc_book.book_num
     *
     * @mbggenerated Wed Apr 29 13:02:59 CST 2020
     */
    public void setBookNum(Integer bookNum) {
        this.bookNum = bookNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_book.status
     *
     * @return the value of sc_book.status
     *
     * @mbggenerated Wed Apr 29 13:02:59 CST 2020
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_book.status
     *
     * @param status the value for sc_book.status
     *
     * @mbggenerated Wed Apr 29 13:02:59 CST 2020
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_book.create_time
     *
     * @return the value of sc_book.create_time
     *
     * @mbggenerated Wed Apr 29 13:02:59 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_book.create_time
     *
     * @param createTime the value for sc_book.create_time
     *
     * @mbggenerated Wed Apr 29 13:02:59 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_book.update_time
     *
     * @return the value of sc_book.update_time
     *
     * @mbggenerated Wed Apr 29 13:02:59 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_book.update_time
     *
     * @param updateTime the value for sc_book.update_time
     *
     * @mbggenerated Wed Apr 29 13:02:59 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}