package com.zx.card.model;

import java.util.Date;

public class BookType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_book_type.id
     *
     * @mbggenerated Wed Apr 29 10:25:19 CST 2020
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_book_type.type_name
     *
     * @mbggenerated Wed Apr 29 10:25:19 CST 2020
     */
    private String typeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_book_type.status
     *
     * @mbggenerated Wed Apr 29 10:25:19 CST 2020
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_book_type.update_time
     *
     * @mbggenerated Wed Apr 29 10:25:19 CST 2020
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_book_type.create_time
     *
     * @mbggenerated Wed Apr 29 10:25:19 CST 2020
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_book_type.id
     *
     * @return the value of sc_book_type.id
     *
     * @mbggenerated Wed Apr 29 10:25:19 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_book_type.id
     *
     * @param id the value for sc_book_type.id
     *
     * @mbggenerated Wed Apr 29 10:25:19 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_book_type.type_name
     *
     * @return the value of sc_book_type.type_name
     *
     * @mbggenerated Wed Apr 29 10:25:19 CST 2020
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_book_type.type_name
     *
     * @param typeName the value for sc_book_type.type_name
     *
     * @mbggenerated Wed Apr 29 10:25:19 CST 2020
     */
    public void setTypeName(String typeName) {
        this.typeName = typeName == null ? null : typeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_book_type.status
     *
     * @return the value of sc_book_type.status
     *
     * @mbggenerated Wed Apr 29 10:25:19 CST 2020
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_book_type.status
     *
     * @param status the value for sc_book_type.status
     *
     * @mbggenerated Wed Apr 29 10:25:19 CST 2020
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_book_type.update_time
     *
     * @return the value of sc_book_type.update_time
     *
     * @mbggenerated Wed Apr 29 10:25:19 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_book_type.update_time
     *
     * @param updateTime the value for sc_book_type.update_time
     *
     * @mbggenerated Wed Apr 29 10:25:19 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_book_type.create_time
     *
     * @return the value of sc_book_type.create_time
     *
     * @mbggenerated Wed Apr 29 10:25:19 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_book_type.create_time
     *
     * @param createTime the value for sc_book_type.create_time
     *
     * @mbggenerated Wed Apr 29 10:25:19 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}