package com.zx.card.model;

import java.util.Date;

public class CardInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_card_info.id
     *
     * @mbggenerated Sat Apr 25 18:11:02 CST 2020
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_card_info.user_id
     *
     * @mbggenerated Sat Apr 25 18:11:02 CST 2020
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_card_info.user_name
     *
     * @mbggenerated Sat Apr 25 18:11:02 CST 2020
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_card_info.user_sex
     *
     * @mbggenerated Sat Apr 25 18:11:02 CST 2020
     */
    private String userSex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_card_info.borrow_num
     *
     * @mbggenerated Sat Apr 25 18:11:02 CST 2020
     */
    private Integer borrowNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_card_info.password
     *
     * @mbggenerated Sat Apr 25 18:11:02 CST 2020
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_card_info.limit_amount
     *
     * @mbggenerated Sat Apr 25 18:11:02 CST 2020
     */
    private Double limitAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_card_info.asset_amount
     *
     * @mbggenerated Sat Apr 25 18:11:02 CST 2020
     */
    private Float assetAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_card_info.status
     *
     * @mbggenerated Sat Apr 25 18:11:02 CST 2020
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_card_info.update_time
     *
     * @mbggenerated Sat Apr 25 18:11:02 CST 2020
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_card_info.create_time
     *
     * @mbggenerated Sat Apr 25 18:11:02 CST 2020
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_card_info.id
     *
     * @return the value of sc_card_info.id
     *
     * @mbggenerated Sat Apr 25 18:11:02 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_card_info.id
     *
     * @param id the value for sc_card_info.id
     *
     * @mbggenerated Sat Apr 25 18:11:02 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_card_info.user_id
     *
     * @return the value of sc_card_info.user_id
     *
     * @mbggenerated Sat Apr 25 18:11:02 CST 2020
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_card_info.user_id
     *
     * @param userId the value for sc_card_info.user_id
     *
     * @mbggenerated Sat Apr 25 18:11:02 CST 2020
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_card_info.user_name
     *
     * @return the value of sc_card_info.user_name
     *
     * @mbggenerated Sat Apr 25 18:11:02 CST 2020
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_card_info.user_name
     *
     * @param userName the value for sc_card_info.user_name
     *
     * @mbggenerated Sat Apr 25 18:11:02 CST 2020
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_card_info.user_sex
     *
     * @return the value of sc_card_info.user_sex
     *
     * @mbggenerated Sat Apr 25 18:11:02 CST 2020
     */
    public String getUserSex() {
        return userSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_card_info.user_sex
     *
     * @param userSex the value for sc_card_info.user_sex
     *
     * @mbggenerated Sat Apr 25 18:11:02 CST 2020
     */
    public void setUserSex(String userSex) {
        this.userSex = userSex == null ? null : userSex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_card_info.borrow_num
     *
     * @return the value of sc_card_info.borrow_num
     *
     * @mbggenerated Sat Apr 25 18:11:02 CST 2020
     */
    public Integer getBorrowNum() {
        return borrowNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_card_info.borrow_num
     *
     * @param borrowNum the value for sc_card_info.borrow_num
     *
     * @mbggenerated Sat Apr 25 18:11:02 CST 2020
     */
    public void setBorrowNum(Integer borrowNum) {
        this.borrowNum = borrowNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_card_info.password
     *
     * @return the value of sc_card_info.password
     *
     * @mbggenerated Sat Apr 25 18:11:02 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_card_info.password
     *
     * @param password the value for sc_card_info.password
     *
     * @mbggenerated Sat Apr 25 18:11:02 CST 2020
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_card_info.limit_amount
     *
     * @return the value of sc_card_info.limit_amount
     *
     * @mbggenerated Sat Apr 25 18:11:02 CST 2020
     */
    public Double getLimitAmount() {
        return limitAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_card_info.limit_amount
     *
     * @param limitAmount the value for sc_card_info.limit_amount
     *
     * @mbggenerated Sat Apr 25 18:11:02 CST 2020
     */
    public void setLimitAmount(Double limitAmount) {
        this.limitAmount = limitAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_card_info.asset_amount
     *
     * @return the value of sc_card_info.asset_amount
     *
     * @mbggenerated Sat Apr 25 18:11:02 CST 2020
     */
    public Float getAssetAmount() {
        return assetAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_card_info.asset_amount
     *
     * @param assetAmount the value for sc_card_info.asset_amount
     *
     * @mbggenerated Sat Apr 25 18:11:02 CST 2020
     */
    public void setAssetAmount(Float assetAmount) {
        this.assetAmount = assetAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_card_info.status
     *
     * @return the value of sc_card_info.status
     *
     * @mbggenerated Sat Apr 25 18:11:02 CST 2020
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_card_info.status
     *
     * @param status the value for sc_card_info.status
     *
     * @mbggenerated Sat Apr 25 18:11:02 CST 2020
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_card_info.update_time
     *
     * @return the value of sc_card_info.update_time
     *
     * @mbggenerated Sat Apr 25 18:11:02 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_card_info.update_time
     *
     * @param updateTime the value for sc_card_info.update_time
     *
     * @mbggenerated Sat Apr 25 18:11:02 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_card_info.create_time
     *
     * @return the value of sc_card_info.create_time
     *
     * @mbggenerated Sat Apr 25 18:11:02 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_card_info.create_time
     *
     * @param createTime the value for sc_card_info.create_time
     *
     * @mbggenerated Sat Apr 25 18:11:02 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}