package com.zx.card.model;

import java.util.Date;

public class Classes {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_classes.id
     *
     * @mbggenerated Sun Apr 05 01:33:23 CST 2020
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_classes.faculty_id
     *
     * @mbggenerated Sun Apr 05 01:33:23 CST 2020
     */
    private Long facultyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_classes.specialty_id
     *
     * @mbggenerated Sun Apr 05 01:33:23 CST 2020
     */
    private Long specialtyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_classes.name
     *
     * @mbggenerated Sun Apr 05 01:33:23 CST 2020
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_classes.year
     *
     * @mbggenerated Sun Apr 05 01:33:23 CST 2020
     */
    private String year;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_classes.status
     *
     * @mbggenerated Sun Apr 05 01:33:23 CST 2020
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_classes.create_time
     *
     * @mbggenerated Sun Apr 05 01:33:23 CST 2020
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_classes.update_time
     *
     * @mbggenerated Sun Apr 05 01:33:23 CST 2020
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_classes.id
     *
     * @return the value of sc_classes.id
     *
     * @mbggenerated Sun Apr 05 01:33:23 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_classes.id
     *
     * @param id the value for sc_classes.id
     *
     * @mbggenerated Sun Apr 05 01:33:23 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_classes.faculty_id
     *
     * @return the value of sc_classes.faculty_id
     *
     * @mbggenerated Sun Apr 05 01:33:23 CST 2020
     */
    public Long getFacultyId() {
        return facultyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_classes.faculty_id
     *
     * @param facultyId the value for sc_classes.faculty_id
     *
     * @mbggenerated Sun Apr 05 01:33:23 CST 2020
     */
    public void setFacultyId(Long facultyId) {
        this.facultyId = facultyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_classes.specialty_id
     *
     * @return the value of sc_classes.specialty_id
     *
     * @mbggenerated Sun Apr 05 01:33:23 CST 2020
     */
    public Long getSpecialtyId() {
        return specialtyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_classes.specialty_id
     *
     * @param specialtyId the value for sc_classes.specialty_id
     *
     * @mbggenerated Sun Apr 05 01:33:23 CST 2020
     */
    public void setSpecialtyId(Long specialtyId) {
        this.specialtyId = specialtyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_classes.name
     *
     * @return the value of sc_classes.name
     *
     * @mbggenerated Sun Apr 05 01:33:23 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_classes.name
     *
     * @param name the value for sc_classes.name
     *
     * @mbggenerated Sun Apr 05 01:33:23 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_classes.year
     *
     * @return the value of sc_classes.year
     *
     * @mbggenerated Sun Apr 05 01:33:23 CST 2020
     */
    public String getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_classes.year
     *
     * @param year the value for sc_classes.year
     *
     * @mbggenerated Sun Apr 05 01:33:23 CST 2020
     */
    public void setYear(String year) {
        this.year = year == null ? null : year.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_classes.status
     *
     * @return the value of sc_classes.status
     *
     * @mbggenerated Sun Apr 05 01:33:23 CST 2020
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_classes.status
     *
     * @param status the value for sc_classes.status
     *
     * @mbggenerated Sun Apr 05 01:33:23 CST 2020
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_classes.create_time
     *
     * @return the value of sc_classes.create_time
     *
     * @mbggenerated Sun Apr 05 01:33:23 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_classes.create_time
     *
     * @param createTime the value for sc_classes.create_time
     *
     * @mbggenerated Sun Apr 05 01:33:23 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_classes.update_time
     *
     * @return the value of sc_classes.update_time
     *
     * @mbggenerated Sun Apr 05 01:33:23 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_classes.update_time
     *
     * @param updateTime the value for sc_classes.update_time
     *
     * @mbggenerated Sun Apr 05 01:33:23 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}