package com.zx.card.model;

import java.util.Date;

public class FacultySpecialty {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_faculty_specialty.id
     *
     * @mbggenerated Sat Apr 04 23:39:54 CST 2020
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_faculty_specialty.name
     *
     * @mbggenerated Sat Apr 04 23:39:54 CST 2020
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_faculty_specialty.type
     *
     * @mbggenerated Sat Apr 04 23:39:54 CST 2020
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_faculty_specialty.parent_id
     *
     * @mbggenerated Sat Apr 04 23:39:54 CST 2020
     */
    private Long parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_faculty_specialty.status
     *
     * @mbggenerated Sat Apr 04 23:39:54 CST 2020
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_faculty_specialty.update_time
     *
     * @mbggenerated Sat Apr 04 23:39:54 CST 2020
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_faculty_specialty.create_time
     *
     * @mbggenerated Sat Apr 04 23:39:54 CST 2020
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_faculty_specialty.id
     *
     * @return the value of sc_faculty_specialty.id
     *
     * @mbggenerated Sat Apr 04 23:39:54 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_faculty_specialty.id
     *
     * @param id the value for sc_faculty_specialty.id
     *
     * @mbggenerated Sat Apr 04 23:39:54 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_faculty_specialty.name
     *
     * @return the value of sc_faculty_specialty.name
     *
     * @mbggenerated Sat Apr 04 23:39:54 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_faculty_specialty.name
     *
     * @param name the value for sc_faculty_specialty.name
     *
     * @mbggenerated Sat Apr 04 23:39:54 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_faculty_specialty.type
     *
     * @return the value of sc_faculty_specialty.type
     *
     * @mbggenerated Sat Apr 04 23:39:54 CST 2020
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_faculty_specialty.type
     *
     * @param type the value for sc_faculty_specialty.type
     *
     * @mbggenerated Sat Apr 04 23:39:54 CST 2020
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_faculty_specialty.parent_id
     *
     * @return the value of sc_faculty_specialty.parent_id
     *
     * @mbggenerated Sat Apr 04 23:39:54 CST 2020
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_faculty_specialty.parent_id
     *
     * @param parentId the value for sc_faculty_specialty.parent_id
     *
     * @mbggenerated Sat Apr 04 23:39:54 CST 2020
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_faculty_specialty.status
     *
     * @return the value of sc_faculty_specialty.status
     *
     * @mbggenerated Sat Apr 04 23:39:54 CST 2020
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_faculty_specialty.status
     *
     * @param status the value for sc_faculty_specialty.status
     *
     * @mbggenerated Sat Apr 04 23:39:54 CST 2020
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_faculty_specialty.update_time
     *
     * @return the value of sc_faculty_specialty.update_time
     *
     * @mbggenerated Sat Apr 04 23:39:54 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_faculty_specialty.update_time
     *
     * @param updateTime the value for sc_faculty_specialty.update_time
     *
     * @mbggenerated Sat Apr 04 23:39:54 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_faculty_specialty.create_time
     *
     * @return the value of sc_faculty_specialty.create_time
     *
     * @mbggenerated Sat Apr 04 23:39:54 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_faculty_specialty.create_time
     *
     * @param createTime the value for sc_faculty_specialty.create_time
     *
     * @mbggenerated Sat Apr 04 23:39:54 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}