package com.zx.card.model;

import java.util.Date;

public class TeacherStudent {

    //diy
    private FacultySpecialty faculty;
    private FacultySpecialty specialty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_teacher_student.id
     *
     * @mbggenerated Sun Apr 05 02:05:34 CST 2020
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_teacher_student.faculty_id
     *
     * @mbggenerated Sun Apr 05 02:05:34 CST 2020
     */
    private Long facultyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_teacher_student.specialty_id
     *
     * @mbggenerated Sun Apr 05 02:05:34 CST 2020
     */
    private Long specialtyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_teacher_student.class_id
     *
     * @mbggenerated Sun Apr 05 02:05:34 CST 2020
     */
    private Long classId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_teacher_student.name
     *
     * @mbggenerated Sun Apr 05 02:05:34 CST 2020
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_teacher_student.year
     *
     * @mbggenerated Sun Apr 05 02:05:34 CST 2020
     */
    private Integer year;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_teacher_student.class_name
     *
     * @mbggenerated Sun Apr 05 02:05:34 CST 2020
     */
    private String className;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_teacher_student.sex
     *
     * @mbggenerated Sun Apr 05 02:05:34 CST 2020
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_teacher_student.birthday
     *
     * @mbggenerated Sun Apr 05 02:05:34 CST 2020
     */
    private String birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_teacher_student.phone
     *
     * @mbggenerated Sun Apr 05 02:05:34 CST 2020
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_teacher_student.id_card
     *
     * @mbggenerated Sun Apr 05 02:05:34 CST 2020
     */
    private String idCard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_teacher_student.role
     *
     * @mbggenerated Sun Apr 05 02:05:34 CST 2020
     */
    private String role;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_teacher_student.status
     *
     * @mbggenerated Sun Apr 05 02:05:34 CST 2020
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_teacher_student.update_time
     *
     * @mbggenerated Sun Apr 05 02:05:34 CST 2020
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_teacher_student.create_time
     *
     * @mbggenerated Sun Apr 05 02:05:34 CST 2020
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_teacher_student.id
     *
     * @return the value of sc_teacher_student.id
     *
     * @mbggenerated Sun Apr 05 02:05:34 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_teacher_student.id
     *
     * @param id the value for sc_teacher_student.id
     *
     * @mbggenerated Sun Apr 05 02:05:34 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_teacher_student.faculty_id
     *
     * @return the value of sc_teacher_student.faculty_id
     *
     * @mbggenerated Sun Apr 05 02:05:34 CST 2020
     */
    public Long getFacultyId() {
        return facultyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_teacher_student.faculty_id
     *
     * @param facultyId the value for sc_teacher_student.faculty_id
     *
     * @mbggenerated Sun Apr 05 02:05:34 CST 2020
     */
    public void setFacultyId(Long facultyId) {
        this.facultyId = facultyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_teacher_student.specialty_id
     *
     * @return the value of sc_teacher_student.specialty_id
     *
     * @mbggenerated Sun Apr 05 02:05:34 CST 2020
     */
    public Long getSpecialtyId() {
        return specialtyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_teacher_student.specialty_id
     *
     * @param specialtyId the value for sc_teacher_student.specialty_id
     *
     * @mbggenerated Sun Apr 05 02:05:34 CST 2020
     */
    public void setSpecialtyId(Long specialtyId) {
        this.specialtyId = specialtyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_teacher_student.class_id
     *
     * @return the value of sc_teacher_student.class_id
     *
     * @mbggenerated Sun Apr 05 02:05:34 CST 2020
     */
    public Long getClassId() {
        return classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_teacher_student.class_id
     *
     * @param classId the value for sc_teacher_student.class_id
     *
     * @mbggenerated Sun Apr 05 02:05:34 CST 2020
     */
    public void setClassId(Long classId) {
        this.classId = classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_teacher_student.name
     *
     * @return the value of sc_teacher_student.name
     *
     * @mbggenerated Sun Apr 05 02:05:34 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_teacher_student.name
     *
     * @param name the value for sc_teacher_student.name
     *
     * @mbggenerated Sun Apr 05 02:05:34 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_teacher_student.year
     *
     * @return the value of sc_teacher_student.year
     *
     * @mbggenerated Sun Apr 05 02:05:34 CST 2020
     */
    public Integer getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_teacher_student.year
     *
     * @param year the value for sc_teacher_student.year
     *
     * @mbggenerated Sun Apr 05 02:05:34 CST 2020
     */
    public void setYear(Integer year) {
        this.year = year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_teacher_student.class_name
     *
     * @return the value of sc_teacher_student.class_name
     *
     * @mbggenerated Sun Apr 05 02:05:34 CST 2020
     */
    public String getClassName() {
        return className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_teacher_student.class_name
     *
     * @param className the value for sc_teacher_student.class_name
     *
     * @mbggenerated Sun Apr 05 02:05:34 CST 2020
     */
    public void setClassName(String className) {
        this.className = className == null ? null : className.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_teacher_student.sex
     *
     * @return the value of sc_teacher_student.sex
     *
     * @mbggenerated Sun Apr 05 02:05:34 CST 2020
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_teacher_student.sex
     *
     * @param sex the value for sc_teacher_student.sex
     *
     * @mbggenerated Sun Apr 05 02:05:34 CST 2020
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_teacher_student.birthday
     *
     * @return the value of sc_teacher_student.birthday
     *
     * @mbggenerated Sun Apr 05 02:05:34 CST 2020
     */
    public String getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_teacher_student.birthday
     *
     * @param birthday the value for sc_teacher_student.birthday
     *
     * @mbggenerated Sun Apr 05 02:05:34 CST 2020
     */
    public void setBirthday(String birthday) {
        this.birthday = birthday == null ? null : birthday.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_teacher_student.phone
     *
     * @return the value of sc_teacher_student.phone
     *
     * @mbggenerated Sun Apr 05 02:05:34 CST 2020
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_teacher_student.phone
     *
     * @param phone the value for sc_teacher_student.phone
     *
     * @mbggenerated Sun Apr 05 02:05:34 CST 2020
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_teacher_student.id_card
     *
     * @return the value of sc_teacher_student.id_card
     *
     * @mbggenerated Sun Apr 05 02:05:34 CST 2020
     */
    public String getIdCard() {
        return idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_teacher_student.id_card
     *
     * @param idCard the value for sc_teacher_student.id_card
     *
     * @mbggenerated Sun Apr 05 02:05:34 CST 2020
     */
    public void setIdCard(String idCard) {
        this.idCard = idCard == null ? null : idCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_teacher_student.role
     *
     * @return the value of sc_teacher_student.role
     *
     * @mbggenerated Sun Apr 05 02:05:34 CST 2020
     */
    public String getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_teacher_student.role
     *
     * @param role the value for sc_teacher_student.role
     *
     * @mbggenerated Sun Apr 05 02:05:34 CST 2020
     */
    public void setRole(String role) {
        this.role = role == null ? null : role.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_teacher_student.status
     *
     * @return the value of sc_teacher_student.status
     *
     * @mbggenerated Sun Apr 05 02:05:34 CST 2020
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_teacher_student.status
     *
     * @param status the value for sc_teacher_student.status
     *
     * @mbggenerated Sun Apr 05 02:05:34 CST 2020
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_teacher_student.update_time
     *
     * @return the value of sc_teacher_student.update_time
     *
     * @mbggenerated Sun Apr 05 02:05:34 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_teacher_student.update_time
     *
     * @param updateTime the value for sc_teacher_student.update_time
     *
     * @mbggenerated Sun Apr 05 02:05:34 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_teacher_student.create_time
     *
     * @return the value of sc_teacher_student.create_time
     *
     * @mbggenerated Sun Apr 05 02:05:34 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_teacher_student.create_time
     *
     * @param createTime the value for sc_teacher_student.create_time
     *
     * @mbggenerated Sun Apr 05 02:05:34 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public FacultySpecialty getFaculty() {
        return faculty;
    }

    public void setFaculty(FacultySpecialty faculty) {
        this.faculty = faculty;
    }

    public FacultySpecialty getSpecialty() {
        return specialty;
    }

    public void setSpecialty(FacultySpecialty specialty) {
        this.specialty = specialty;
    }
}