package com.zx.card.dao.generate;

import com.zx.card.model.AssetHistory;
import com.zx.card.model.AssetHistoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AssetHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_asset_history
     *
     * @mbggenerated Sat Apr 25 18:05:45 CST 2020
     */
    int countByExample(AssetHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_asset_history
     *
     * @mbggenerated Sat Apr 25 18:05:45 CST 2020
     */
    int deleteByExample(AssetHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_asset_history
     *
     * @mbggenerated Sat Apr 25 18:05:45 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_asset_history
     *
     * @mbggenerated Sat Apr 25 18:05:45 CST 2020
     */
    int insert(AssetHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_asset_history
     *
     * @mbggenerated Sat Apr 25 18:05:45 CST 2020
     */
    int insertSelective(AssetHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_asset_history
     *
     * @mbggenerated Sat Apr 25 18:05:45 CST 2020
     */
    List<AssetHistory> selectByExample(AssetHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_asset_history
     *
     * @mbggenerated Sat Apr 25 18:05:45 CST 2020
     */
    AssetHistory selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_asset_history
     *
     * @mbggenerated Sat Apr 25 18:05:45 CST 2020
     */
    int updateByExampleSelective(@Param("record") AssetHistory record, @Param("example") AssetHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_asset_history
     *
     * @mbggenerated Sat Apr 25 18:05:45 CST 2020
     */
    int updateByExample(@Param("record") AssetHistory record, @Param("example") AssetHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_asset_history
     *
     * @mbggenerated Sat Apr 25 18:05:45 CST 2020
     */
    int updateByPrimaryKeySelective(AssetHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_asset_history
     *
     * @mbggenerated Sat Apr 25 18:05:45 CST 2020
     */
    int updateByPrimaryKey(AssetHistory record);
}