package com.zx.card.dao.generate;

import com.zx.card.model.Book;
import com.zx.card.model.BookExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BookMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_book
     *
     * @mbggenerated Wed Apr 29 13:02:59 CST 2020
     */
    int countByExample(BookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_book
     *
     * @mbggenerated Wed Apr 29 13:02:59 CST 2020
     */
    int deleteByExample(BookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_book
     *
     * @mbggenerated Wed Apr 29 13:02:59 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_book
     *
     * @mbggenerated Wed Apr 29 13:02:59 CST 2020
     */
    int insert(Book record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_book
     *
     * @mbggenerated Wed Apr 29 13:02:59 CST 2020
     */
    int insertSelective(Book record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_book
     *
     * @mbggenerated Wed Apr 29 13:02:59 CST 2020
     */
    List<Book> selectByExample(BookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_book
     *
     * @mbggenerated Wed Apr 29 13:02:59 CST 2020
     */
    Book selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_book
     *
     * @mbggenerated Wed Apr 29 13:02:59 CST 2020
     */
    int updateByExampleSelective(@Param("record") Book record, @Param("example") BookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_book
     *
     * @mbggenerated Wed Apr 29 13:02:59 CST 2020
     */
    int updateByExample(@Param("record") Book record, @Param("example") BookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_book
     *
     * @mbggenerated Wed Apr 29 13:02:59 CST 2020
     */
    int updateByPrimaryKeySelective(Book record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_book
     *
     * @mbggenerated Wed Apr 29 13:02:59 CST 2020
     */
    int updateByPrimaryKey(Book record);
}