package com.zx.card.dao.generate;

import com.zx.card.model.BorrowRecord;
import com.zx.card.model.BorrowRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BorrowRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_borrow_record
     *
     * @mbggenerated Wed Apr 29 17:03:03 CST 2020
     */
    int countByExample(BorrowRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_borrow_record
     *
     * @mbggenerated Wed Apr 29 17:03:03 CST 2020
     */
    int deleteByExample(BorrowRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_borrow_record
     *
     * @mbggenerated Wed Apr 29 17:03:03 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_borrow_record
     *
     * @mbggenerated Wed Apr 29 17:03:03 CST 2020
     */
    int insert(BorrowRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_borrow_record
     *
     * @mbggenerated Wed Apr 29 17:03:03 CST 2020
     */
    int insertSelective(BorrowRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_borrow_record
     *
     * @mbggenerated Wed Apr 29 17:03:03 CST 2020
     */
    List<BorrowRecord> selectByExample(BorrowRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_borrow_record
     *
     * @mbggenerated Wed Apr 29 17:03:03 CST 2020
     */
    BorrowRecord selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_borrow_record
     *
     * @mbggenerated Wed Apr 29 17:03:03 CST 2020
     */
    int updateByExampleSelective(@Param("record") BorrowRecord record, @Param("example") BorrowRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_borrow_record
     *
     * @mbggenerated Wed Apr 29 17:03:03 CST 2020
     */
    int updateByExample(@Param("record") BorrowRecord record, @Param("example") BorrowRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_borrow_record
     *
     * @mbggenerated Wed Apr 29 17:03:03 CST 2020
     */
    int updateByPrimaryKeySelective(BorrowRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_borrow_record
     *
     * @mbggenerated Wed Apr 29 17:03:03 CST 2020
     */
    int updateByPrimaryKey(BorrowRecord record);
}