package com.zx.card.dao.generate;

import com.zx.card.model.Canteen;
import com.zx.card.model.CanteenExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CanteenMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_canteen
     *
     * @mbggenerated Wed Apr 15 19:50:38 CST 2020
     */
    int countByExample(CanteenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_canteen
     *
     * @mbggenerated Wed Apr 15 19:50:38 CST 2020
     */
    int deleteByExample(CanteenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_canteen
     *
     * @mbggenerated Wed Apr 15 19:50:38 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_canteen
     *
     * @mbggenerated Wed Apr 15 19:50:38 CST 2020
     */
    int insert(Canteen record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_canteen
     *
     * @mbggenerated Wed Apr 15 19:50:38 CST 2020
     */
    int insertSelective(Canteen record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_canteen
     *
     * @mbggenerated Wed Apr 15 19:50:38 CST 2020
     */
    List<Canteen> selectByExample(CanteenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_canteen
     *
     * @mbggenerated Wed Apr 15 19:50:38 CST 2020
     */
    Canteen selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_canteen
     *
     * @mbggenerated Wed Apr 15 19:50:38 CST 2020
     */
    int updateByExampleSelective(@Param("record") Canteen record, @Param("example") CanteenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_canteen
     *
     * @mbggenerated Wed Apr 15 19:50:38 CST 2020
     */
    int updateByExample(@Param("record") Canteen record, @Param("example") CanteenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_canteen
     *
     * @mbggenerated Wed Apr 15 19:50:38 CST 2020
     */
    int updateByPrimaryKeySelective(Canteen record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_canteen
     *
     * @mbggenerated Wed Apr 15 19:50:38 CST 2020
     */
    int updateByPrimaryKey(Canteen record);
}