package com.zx.card.dao.generate;

import com.zx.card.model.CardInfo;
import com.zx.card.model.CardInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CardInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_card_info
     *
     * @mbggenerated Sat Apr 25 18:11:02 CST 2020
     */
    int countByExample(CardInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_card_info
     *
     * @mbggenerated Sat Apr 25 18:11:02 CST 2020
     */
    int deleteByExample(CardInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_card_info
     *
     * @mbggenerated Sat Apr 25 18:11:02 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_card_info
     *
     * @mbggenerated Sat Apr 25 18:11:02 CST 2020
     */
    int insert(CardInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_card_info
     *
     * @mbggenerated Sat Apr 25 18:11:02 CST 2020
     */
    int insertSelective(CardInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_card_info
     *
     * @mbggenerated Sat Apr 25 18:11:02 CST 2020
     */
    List<CardInfo> selectByExample(CardInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_card_info
     *
     * @mbggenerated Sat Apr 25 18:11:02 CST 2020
     */
    CardInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_card_info
     *
     * @mbggenerated Sat Apr 25 18:11:02 CST 2020
     */
    int updateByExampleSelective(@Param("record") CardInfo record, @Param("example") CardInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_card_info
     *
     * @mbggenerated Sat Apr 25 18:11:02 CST 2020
     */
    int updateByExample(@Param("record") CardInfo record, @Param("example") CardInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_card_info
     *
     * @mbggenerated Sat Apr 25 18:11:02 CST 2020
     */
    int updateByPrimaryKeySelective(CardInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_card_info
     *
     * @mbggenerated Sat Apr 25 18:11:02 CST 2020
     */
    int updateByPrimaryKey(CardInfo record);
}