package com.zx.card.dao.generate;

import com.zx.card.model.Classes;
import com.zx.card.model.ClassesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ClassesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_classes
     *
     * @mbggenerated Sun Apr 05 01:33:23 CST 2020
     */
    int countByExample(ClassesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_classes
     *
     * @mbggenerated Sun Apr 05 01:33:23 CST 2020
     */
    int deleteByExample(ClassesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_classes
     *
     * @mbggenerated Sun Apr 05 01:33:23 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_classes
     *
     * @mbggenerated Sun Apr 05 01:33:23 CST 2020
     */
    int insert(Classes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_classes
     *
     * @mbggenerated Sun Apr 05 01:33:23 CST 2020
     */
    int insertSelective(Classes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_classes
     *
     * @mbggenerated Sun Apr 05 01:33:23 CST 2020
     */
    List<Classes> selectByExample(ClassesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_classes
     *
     * @mbggenerated Sun Apr 05 01:33:23 CST 2020
     */
    Classes selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_classes
     *
     * @mbggenerated Sun Apr 05 01:33:23 CST 2020
     */
    int updateByExampleSelective(@Param("record") Classes record, @Param("example") ClassesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_classes
     *
     * @mbggenerated Sun Apr 05 01:33:23 CST 2020
     */
    int updateByExample(@Param("record") Classes record, @Param("example") ClassesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_classes
     *
     * @mbggenerated Sun Apr 05 01:33:23 CST 2020
     */
    int updateByPrimaryKeySelective(Classes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_classes
     *
     * @mbggenerated Sun Apr 05 01:33:23 CST 2020
     */
    int updateByPrimaryKey(Classes record);
}