package com.zx.card.dao.generate;

import com.zx.card.model.FacultySpecialty;
import com.zx.card.model.FacultySpecialtyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FacultySpecialtyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_faculty_specialty
     *
     * @mbggenerated Sat Apr 04 23:39:54 CST 2020
     */
    int countByExample(FacultySpecialtyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_faculty_specialty
     *
     * @mbggenerated Sat Apr 04 23:39:54 CST 2020
     */
    int deleteByExample(FacultySpecialtyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_faculty_specialty
     *
     * @mbggenerated Sat Apr 04 23:39:54 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_faculty_specialty
     *
     * @mbggenerated Sat Apr 04 23:39:54 CST 2020
     */
    int insert(FacultySpecialty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_faculty_specialty
     *
     * @mbggenerated Sat Apr 04 23:39:54 CST 2020
     */
    int insertSelective(FacultySpecialty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_faculty_specialty
     *
     * @mbggenerated Sat Apr 04 23:39:54 CST 2020
     */
    List<FacultySpecialty> selectByExample(FacultySpecialtyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_faculty_specialty
     *
     * @mbggenerated Sat Apr 04 23:39:54 CST 2020
     */
    FacultySpecialty selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_faculty_specialty
     *
     * @mbggenerated Sat Apr 04 23:39:54 CST 2020
     */
    int updateByExampleSelective(@Param("record") FacultySpecialty record, @Param("example") FacultySpecialtyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_faculty_specialty
     *
     * @mbggenerated Sat Apr 04 23:39:54 CST 2020
     */
    int updateByExample(@Param("record") FacultySpecialty record, @Param("example") FacultySpecialtyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_faculty_specialty
     *
     * @mbggenerated Sat Apr 04 23:39:54 CST 2020
     */
    int updateByPrimaryKeySelective(FacultySpecialty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_faculty_specialty
     *
     * @mbggenerated Sat Apr 04 23:39:54 CST 2020
     */
    int updateByPrimaryKey(FacultySpecialty record);
}