package com.zx.card.dao.generate;

import com.zx.card.model.Library;
import com.zx.card.model.LibraryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LibraryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_library
     *
     * @mbggenerated Wed Apr 15 20:12:27 CST 2020
     */
    int countByExample(LibraryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_library
     *
     * @mbggenerated Wed Apr 15 20:12:27 CST 2020
     */
    int deleteByExample(LibraryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_library
     *
     * @mbggenerated Wed Apr 15 20:12:27 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_library
     *
     * @mbggenerated Wed Apr 15 20:12:27 CST 2020
     */
    int insert(Library record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_library
     *
     * @mbggenerated Wed Apr 15 20:12:27 CST 2020
     */
    int insertSelective(Library record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_library
     *
     * @mbggenerated Wed Apr 15 20:12:27 CST 2020
     */
    List<Library> selectByExample(LibraryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_library
     *
     * @mbggenerated Wed Apr 15 20:12:27 CST 2020
     */
    Library selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_library
     *
     * @mbggenerated Wed Apr 15 20:12:27 CST 2020
     */
    int updateByExampleSelective(@Param("record") Library record, @Param("example") LibraryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_library
     *
     * @mbggenerated Wed Apr 15 20:12:27 CST 2020
     */
    int updateByExample(@Param("record") Library record, @Param("example") LibraryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_library
     *
     * @mbggenerated Wed Apr 15 20:12:27 CST 2020
     */
    int updateByPrimaryKeySelective(Library record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_library
     *
     * @mbggenerated Wed Apr 15 20:12:27 CST 2020
     */
    int updateByPrimaryKey(Library record);
}