package com.zx.card.dao.generate;

import com.zx.card.model.Supermarket;
import com.zx.card.model.SupermarketExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SupermarketMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_supermarket
     *
     * @mbggenerated Wed Apr 15 21:55:42 CST 2020
     */
    int countByExample(SupermarketExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_supermarket
     *
     * @mbggenerated Wed Apr 15 21:55:42 CST 2020
     */
    int deleteByExample(SupermarketExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_supermarket
     *
     * @mbggenerated Wed Apr 15 21:55:42 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_supermarket
     *
     * @mbggenerated Wed Apr 15 21:55:42 CST 2020
     */
    int insert(Supermarket record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_supermarket
     *
     * @mbggenerated Wed Apr 15 21:55:42 CST 2020
     */
    int insertSelective(Supermarket record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_supermarket
     *
     * @mbggenerated Wed Apr 15 21:55:42 CST 2020
     */
    List<Supermarket> selectByExample(SupermarketExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_supermarket
     *
     * @mbggenerated Wed Apr 15 21:55:42 CST 2020
     */
    Supermarket selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_supermarket
     *
     * @mbggenerated Wed Apr 15 21:55:42 CST 2020
     */
    int updateByExampleSelective(@Param("record") Supermarket record, @Param("example") SupermarketExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_supermarket
     *
     * @mbggenerated Wed Apr 15 21:55:42 CST 2020
     */
    int updateByExample(@Param("record") Supermarket record, @Param("example") SupermarketExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_supermarket
     *
     * @mbggenerated Wed Apr 15 21:55:42 CST 2020
     */
    int updateByPrimaryKeySelective(Supermarket record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_supermarket
     *
     * @mbggenerated Wed Apr 15 21:55:42 CST 2020
     */
    int updateByPrimaryKey(Supermarket record);
}