package com.zx.card.dao.generate;

import com.zx.card.model.TeacherStudent;
import com.zx.card.model.TeacherStudentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TeacherStudentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_teacher_student
     *
     * @mbggenerated Sun Apr 05 02:05:34 CST 2020
     */
    int countByExample(TeacherStudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_teacher_student
     *
     * @mbggenerated Sun Apr 05 02:05:34 CST 2020
     */
    int deleteByExample(TeacherStudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_teacher_student
     *
     * @mbggenerated Sun Apr 05 02:05:34 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_teacher_student
     *
     * @mbggenerated Sun Apr 05 02:05:34 CST 2020
     */
    int insert(TeacherStudent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_teacher_student
     *
     * @mbggenerated Sun Apr 05 02:05:34 CST 2020
     */
    int insertSelective(TeacherStudent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_teacher_student
     *
     * @mbggenerated Sun Apr 05 02:05:34 CST 2020
     */
    List<TeacherStudent> selectByExample(TeacherStudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_teacher_student
     *
     * @mbggenerated Sun Apr 05 02:05:34 CST 2020
     */
    TeacherStudent selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_teacher_student
     *
     * @mbggenerated Sun Apr 05 02:05:34 CST 2020
     */
    int updateByExampleSelective(@Param("record") TeacherStudent record, @Param("example") TeacherStudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_teacher_student
     *
     * @mbggenerated Sun Apr 05 02:05:34 CST 2020
     */
    int updateByExample(@Param("record") TeacherStudent record, @Param("example") TeacherStudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_teacher_student
     *
     * @mbggenerated Sun Apr 05 02:05:34 CST 2020
     */
    int updateByPrimaryKeySelective(TeacherStudent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_teacher_student
     *
     * @mbggenerated Sun Apr 05 02:05:34 CST 2020
     */
    int updateByPrimaryKey(TeacherStudent record);
}